package Vistas;

import Controlador.CrudeCliente;
import Controlador.CrudeMantencion;
import Controlador.CrudeVehiculo;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import taller.Cliente;
import taller.Mantencion;
import taller.Vehiculo;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Javier Ignacio Parraguirre Lizarraga 20/10/23
 */
public class Vista extends javax.swing.JFrame {


    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtRut = new javax.swing.JTextField();
        infoCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApe1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApe2 = new javax.swing.JTextField();
        btnIngresoCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaClientes = new javax.swing.JTable();
        btnModificarClienteSQL = new javax.swing.JButton();
        listaClientes = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtClienteVehiculo = new javax.swing.JTextField();
        infoVehiculo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPatente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAgnoFab = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        btnIngresoVehiculo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListaVehiculo = new javax.swing.JTable();
        listaClientes1 = new javax.swing.JButton();
        txtMarca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        listaVehiculo = new javax.swing.JButton();
        btnModificarVehiculo = new javax.swing.JButton();
        btnEliminarVehiculo = new javax.swing.JButton();
        btnModificarVehiculoSQL = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtVin = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPatenteman = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnIngresoman = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListaMantencion = new javax.swing.JTable();
        btnListarman = new javax.swing.JButton();
        btnModificarman = new javax.swing.JButton();
        btnEliminarman = new javax.swing.JButton();
        infoMantencion = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        tituloDesc = new javax.swing.JLabel();
        listaVehiculo1 = new javax.swing.JButton();
        btnModificarManSQL = new javax.swing.JButton();
        tituloDesc1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtKiloMantencion = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        txtFechaing = new javax.swing.JFormattedTextField();
        txtFechasal = new javax.swing.JFormattedTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDesMan = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        comboBuscar = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblBuscar = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Taller");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });

        infoCliente.setText("Ingreso de Clientes");

        jLabel3.setText("RUT");

        jLabel4.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel5.setText("Apellido Paterno");

        txtApe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApe1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Apellido Materno");

        txtApe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApe2ActionPerformed(evt);
            }
        });

        btnIngresoCliente.setText("Guardar cliente");
        btnIngresoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoClienteActionPerformed(evt);
            }
        });

        tblListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblListaClientes);

        btnModificarClienteSQL.setVisible(false);
        btnModificarClienteSQL.setText("Modificar Cliente");
        btnModificarClienteSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteSQLActionPerformed(evt);
            }
        });

        listaClientes.setText("Lista de clientes");
        listaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClientesActionPerformed(evt);
            }
        });

        btnModificarCliente.setText("Modificar cliente");
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setText("Eliminar cliente");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        jLabel15.setText("Correo");

        jLabel16.setText("Telefono");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModificarClienteSQL)
                    .addComponent(btnIngresoCliente)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtApe2)
                        .addComponent(txtApe1)
                        .addComponent(txtNombre)
                        .addComponent(txtRut, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                        .addComponent(txtTelefono)
                        .addComponent(txtCorreo)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(infoCliente)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel16)
                                .addComponent(jLabel15))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(listaClientes)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCliente))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(213, 213, 213))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(372, 372, 372)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnIngresoCliente)
                                    .addComponent(btnModificarClienteSQL)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(infoCliente)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(219, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", jPanel3);

        txtClienteVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteVehiculoActionPerformed(evt);
            }
        });

        infoVehiculo.setText("Ingreso Vehiculo");

        jLabel7.setText("RUT Dueño");

        jLabel8.setText("Patente");

        txtPatente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatenteActionPerformed(evt);
            }
        });

        jLabel9.setText("Año Fabricación");

        txtAgnoFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgnoFabActionPerformed(evt);
            }
        });

        jLabel10.setText("Color");

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        btnIngresoVehiculo.setText("Guardar Vehiculo");
        btnIngresoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoVehiculoActionPerformed(evt);
            }
        });

        tblListaVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblListaVehiculo);

        listaClientes1.setText("Lista de clientes");
        listaClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClientes1ActionPerformed(evt);
            }
        });

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        jLabel11.setText("Marca");

        jLabel12.setText("Modelo");

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        listaVehiculo.setText("Lista Vehiculo");
        listaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaVehiculoActionPerformed(evt);
            }
        });

        btnModificarVehiculo.setText("Modificar Vehiculo");
        btnModificarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVehiculoActionPerformed(evt);
            }
        });

        btnEliminarVehiculo.setText("Eliminar Vehiculo");
        btnEliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVehiculoActionPerformed(evt);
            }
        });

        btnModificarVehiculoSQL.setVisible(false);
        btnModificarVehiculoSQL.setText("Modificar Vehiculo");
        btnModificarVehiculoSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarVehiculoSQLActionPerformed(evt);
            }
        });

        jLabel17.setText("VIN");

        txtVin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtModelo)
                    .addComponent(txtMarca)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtColor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAgnoFab, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPatente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClienteVehiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                        .addComponent(jLabel7)
                        .addComponent(infoVehiculo)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel17))
                    .addComponent(txtVin))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(listaClientes1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(listaVehiculo)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarVehiculo)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarVehiculo))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnIngresoVehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarVehiculoSQL)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(200, 200, 200))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(listaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModificarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(listaClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(infoVehiculo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClienteVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAgnoFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarVehiculoSQL)
                    .addComponent(btnIngresoVehiculo))
                .addGap(179, 179, 179))
        );

        jTabbedPane1.addTab("Vehiculo", jPanel4);

        jLabel2.setText("Ingrese Patente");

        txtPatenteman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatentemanActionPerformed(evt);
            }
        });

        jLabel13.setText("Ingrese Fecha de ingreso ");

        jLabel14.setText("Ingrese Fecha de Salida");

        btnIngresoman.setText("Ingresar Mantencion");
        btnIngresoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresomanActionPerformed(evt);
            }
        });

        tblListaMantencion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListaMantencion.setCellSelectionEnabled(true);
        jScrollPane3.setViewportView(tblListaMantencion);

        btnListarman.setText("Lista Mantencion");
        btnListarman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarmanActionPerformed(evt);
            }
        });

        btnModificarman.setText("Modificar Mantencion");
        btnModificarman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarmanActionPerformed(evt);
            }
        });

        btnEliminarman.setText("Eliminar Mantencion");
        btnEliminarman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarmanActionPerformed(evt);
            }
        });

        infoMantencion.setText("Ingreso de Mantencion");

        comboEstado.setMaximumRowCount(2);
        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Completado" }));

        tituloDesc.setText("Descripcion");

        listaVehiculo1.setText("Lista Vehiculo");
        listaVehiculo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaVehiculo1ActionPerformed(evt);
            }
        });

        btnModificarManSQL.setText("Modificar Mantencion");
        btnModificarManSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarManSQLActionPerformed(evt);
            }
        });

        tituloDesc1.setText("Estado");

        jLabel18.setText("Kilometraje del vehiculo");

        txtKiloMantencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKiloMantencionActionPerformed(evt);
            }
        });

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane4.setViewportView(txtDesc);

        txtFechaing.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        txtFechaing.setText("dd-mm-yyyy");
        txtFechaing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaingActionPerformed(evt);
            }
        });
        txtFechaing.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.getClickCount()==1) {
                    String selected = txtPatenteman.getText();
                    CrudeVehiculo crud = new CrudeVehiculo();
                    Vehiculo vic=crud.Buscar(selected);
                    if(selected.toString().equals(vic.getPatente()))
                    txtKiloMantencion.setText(String.valueOf(vic.getKilometraje()));
                }
            }
        });

        txtFechasal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        txtFechasal.setText("dd-mm-yyyy");
        txtFechasal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechasalActionPerformed(evt);
            }
        });

        txtDesMan.setEditable(false);
        txtDesMan.setBackground(new java.awt.Color(214, 214, 214));
        txtDesMan.setColumns(20);
        txtDesMan.setForeground(new java.awt.Color(0, 0, 0));
        txtDesMan.setRows(5);
        txtDesMan.setCaretColor(new java.awt.Color(51, 51, 51));
        txtDesMan.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtDesMan.setFocusable(false);
        jScrollPane6.setViewportView(txtDesMan);
        txtDesMan.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnIngresoman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificarManSQL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPatenteman, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtKiloMantencion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tituloDesc1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFechaing, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFechasal, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(infoMantencion)
                    .addComponent(tituloDesc)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(listaVehiculo1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarman))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarman)
                    .addComponent(btnModificarman)
                    .addComponent(btnEliminarman)
                    .addComponent(infoMantencion)
                    .addComponent(listaVehiculo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPatenteman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFechaing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFechasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtKiloMantencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tituloDesc1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(tituloDesc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnIngresoman)
                                .addComponent(btnModificarManSQL)))
                        .addComponent(jScrollPane3))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mantencion", jPanel5);

        comboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Vehiculo", "Mantencion" }));
        comboBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBuscarActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblBuscar);

        jLabel19.setText("Elemento que desea buscar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoClienteActionPerformed

        String rut=txtRut.getText();
        String dv= rut.substring(rut.length()-1);
        rut = rut.substring(0, rut.length()-1);
        String nomb=txtNombre.getText();
        String ape1=txtApe1.getText();
        String ape2=txtApe2.getText();
        String telefono=txtTelefono.getText();
        String correo=txtCorreo.getText();
        Cliente cli=new Cliente(rut,dv,nomb,ape1,ape2,telefono,correo);   
        CrudeCliente crud=new CrudeCliente();
        crud.Agregar(cli);
        
    }//GEN-LAST:event_btnIngresoClienteActionPerformed

    private void txtApe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApe1ActionPerformed

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApe2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApe2ActionPerformed

    private void btnModificarClienteSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteSQLActionPerformed
        // TODO add your handling code here:
        String rut=txtRut.getText();
        String dv= rut.substring(rut.length()-1);
        rut = rut.substring(0, 8);
        String nomb=txtNombre.getText();
        String ape1=txtApe1.getText();
        String ape2=txtApe2.getText();
        String telefono=txtTelefono.getText();
        String correo=txtCorreo.getText();
        Cliente cli=new Cliente(rut,dv,nomb,ape1,ape2,telefono,correo);
        CrudeCliente crud=new CrudeCliente();
        crud.Modificar(cli);
        txtRut.setEditable(true);
        infoCliente.setText("Ingreso Cliente:");
        btnModificarClienteSQL.setVisible(false);
    }//GEN-LAST:event_btnModificarClienteSQLActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
        String eliminarCliente = JOptionPane.showInputDialog(rootPane, "Ingrese el RUT del cliente que desea eliminar");
        CrudeCliente crud=new CrudeCliente();
        crud.Eliminar(eliminarCliente);
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        // TODO add your handling code here:
            String modificarCliente = JOptionPane.showInputDialog(rootPane, "Ingrese el rut del usuario que desea modificar");
            modificarCliente = modificarCliente.substring(0, 8);
            CrudeCliente crud=new CrudeCliente();
            Cliente cli = crud.Buscar(modificarCliente);
            txtRut.setText(cli.getRut()+"-"+cli.getDv());
            txtNombre.setText(cli.getNombre());
            txtApe1.setText(cli.getApe1());
            txtApe2.setText(cli.getApe2());
            txtTelefono.setText(cli.getTelefono());
            txtCorreo.setText(cli.getCorreo());
            infoCliente.setText("Modificar Cliente:"+modificarCliente);
            txtRut.setEditable(false);
            btnModificarClienteSQL.setVisible(true);
            
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void listaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClientesActionPerformed
        // TODO add your handling code here:
        CrudeCliente crud=new CrudeCliente();
        tblListaClientes.setModel(crud.listaClientes());

    }//GEN-LAST:event_listaClientesActionPerformed

    private void txtClienteVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteVehiculoActionPerformed

    private void txtPatenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatenteActionPerformed

    private void txtAgnoFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgnoFabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgnoFabActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void btnIngresoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoVehiculoActionPerformed
        // TODO add your handling code here:
        String patente=txtPatente.getText();
        String agno=txtAgnoFab.getText();
        String color=txtColor.getText();
        String marca=txtMarca.getText();
        String modelo=txtModelo.getText();
        String rut_cliente = txtClienteVehiculo.getText();
        String vin=txtVin.getText();
        int agno_fab = Integer.parseInt(agno);
        CrudeCliente crudCli=new CrudeCliente();
        Cliente cli = crudCli.Buscar(rut_cliente);
        Vehiculo vic=new Vehiculo(patente,agno_fab,color,marca,modelo,cli,0,vin);   
        CrudeVehiculo crudVic=new CrudeVehiculo();
        try {
            crudVic.Agregar(vic, cli);
        } catch (ParseException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnIngresoVehiculoActionPerformed

    private void listaClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClientes1ActionPerformed
        // TODO add your handling code here:
        CrudeCliente crud=new CrudeCliente();
        tblListaVehiculo.setModel(crud.listaClientes());
    }//GEN-LAST:event_listaClientes1ActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void listaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaVehiculoActionPerformed
        // TODO add your handling code here:
        CrudeVehiculo crud=new CrudeVehiculo();
        tblListaVehiculo.setModel(crud.listaVehiculo());
    }//GEN-LAST:event_listaVehiculoActionPerformed

    private void btnModificarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVehiculoActionPerformed
        // TODO add your handling code here:
        String modificarvehiculo = JOptionPane.showInputDialog(rootPane, "Ingrese la patente del vehiculo que desea modificar");
        CrudeVehiculo crud=new CrudeVehiculo();
        Vehiculo vic = crud.Buscar(modificarvehiculo);
        txtClienteVehiculo.setText(vic.getRut_cliente().getRut()+"-"+vic.getRut_cliente().getDv());
        txtPatente.setText(vic.getPatente());
        txtAgnoFab.setText(String.valueOf(vic.getAgno_fab()));
        txtColor.setText(vic.getColor());
        txtMarca.setText(vic.getMarca());
        txtModelo.setText(vic.getModelo());
        txtVin.setText(vic.getVin());
        infoVehiculo.setText("Modificar Vehiculo Patente: "+modificarvehiculo);
        txtPatente.setEditable(false);
        btnModificarVehiculoSQL.setVisible(true);
        btnIngresoVehiculo.setVisible(false);
    }//GEN-LAST:event_btnModificarVehiculoActionPerformed

    private void btnEliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVehiculoActionPerformed
        // TODO add your handling code here:
        String eliminarVehiculo = JOptionPane.showInputDialog(rootPane, "Ingrese la patente del vehiculo que desea eliminar");
        CrudeVehiculo crud=new CrudeVehiculo();
        crud.Eliminar(eliminarVehiculo);
    }//GEN-LAST:event_btnEliminarVehiculoActionPerformed

    private void btnModificarVehiculoSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarVehiculoSQLActionPerformed
        // TODO add your handling code here:
        String rut_cliente=txtClienteVehiculo.getText();
        rut_cliente = rut_cliente.substring(0, 8);
        String patente=txtPatente.getText();
        String agno=txtAgnoFab.getText();
        String color=txtColor.getText();
        String marca=txtMarca.getText();
        String modelo=txtModelo.getText();
        String vin=txtVin.getText();
        CrudeCliente crudeCli=new CrudeCliente();
        int agno_fab = Integer.parseInt(agno);
        Vehiculo vic=new Vehiculo(patente,agno_fab,color,marca,modelo,crudeCli.Buscar(rut_cliente),0,vin);
        CrudeVehiculo crud=new CrudeVehiculo();
        crud.Modificar(vic);
        txtPatente.setEditable(true);
        infoVehiculo.setText("Ingreso Vehiculo: ");
        btnModificarVehiculoSQL.setVisible(false);
        btnIngresoVehiculo.setVisible(true);
    }//GEN-LAST:event_btnModificarVehiculoSQLActionPerformed

    private void btnEliminarmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarmanActionPerformed
        // TODO add your handling code here:
        String eliminarMantencion = JOptionPane.showInputDialog(rootPane, "Ingrese la id de la mantencion que desea eliminar");
        CrudeMantencion crud=new CrudeMantencion();
        crud.Eliminar(eliminarMantencion);
    }//GEN-LAST:event_btnEliminarmanActionPerformed

    private void btnModificarmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarmanActionPerformed
        try {
            // TODO add your handling code here:
            String modificar = JOptionPane.showInputDialog(rootPane, "Ingrese la id de la mantencion que desea modificar");
            int modificarmant = Integer.parseInt(modificar);
            CrudeMantencion crud=new CrudeMantencion();
            Mantencion man = crud.Buscar(modificarmant);
            SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
            txtPatenteman.setText(man.getVehiculo().getPatente());
            txtFechaing.setText(formato.format(man.getFec_ing()));
            txtFechasal.setText(formato.format(man.getFec_sal()));
            comboEstado.setSelectedIndex(man.verificaEstado1(man.isEstado()));
            txtDesc.setText(man.getDescripcion());
            infoMantencion.setText("Modificar Mantencion numero: "+modificarmant);
            txtPatenteman.setEditable(false);
            btnModificarManSQL.setVisible(true);
            btnIngresoman.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnModificarmanActionPerformed

    private void btnListarmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarmanActionPerformed
        // TODO add your handling code here:
        CrudeMantencion crud=new CrudeMantencion();
        tblListaMantencion.setModel(crud.listaMantencion());
        tblListaMantencion.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 1) {
            JTable target = (JTable)e.getSource();
                int row = target.getSelectedRow();
                int column = target.getSelectedColumn();
                // do some action if appropriate column
                        if(column==4){
                            txtDesMan.setText((String) tblListaMantencion.getValueAt(row, column));    
                        }
                }
            }
        });
    }//GEN-LAST:event_btnListarmanActionPerformed

    private void btnIngresomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresomanActionPerformed
        // TODO add your handling code here:
        int id = 0;
        String patenteman=txtPatenteman.getText();
        String fec_ing=txtFechaing.getText();
        String fec_sal=txtFechasal.getText();
        int estado=comboEstado.getSelectedIndex();
        String descripcion=txtDesc.getText();
        int kilo_man =0;
        CrudeVehiculo crudVic=new CrudeVehiculo();
        Vehiculo vic = crudVic.Buscar(patenteman);
        Date fecha_ing = new Date(); 
        Date fecha_sal = new Date();
         Mantencion man = new Mantencion();
        boolean estado_verif = man.verificaEstado(estado);
        try{
          SimpleDateFormat formato=new SimpleDateFormat("dd-mm-yyyy");
            fecha_ing=formato.parse(fec_ing);
            fecha_sal=formato.parse(fec_sal);
        } catch(ParseException ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        man = new Mantencion(id, fecha_ing,fecha_sal,estado_verif,vic, descripcion,kilo_man);
        CrudeMantencion crudMan=new CrudeMantencion();
        try {
            crudMan.Agregar(man, vic);
        } catch (ParseException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIngresomanActionPerformed

    private void txtPatentemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatentemanActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_txtPatentemanActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void listaVehiculo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaVehiculo1ActionPerformed
        // TODO add your handling code here:
        CrudeVehiculo crud=new CrudeVehiculo();
        tblListaMantencion.setModel(crud.listaVehiculo());
    }//GEN-LAST:event_listaVehiculo1ActionPerformed

    private void btnModificarManSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarManSQLActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(infoMantencion.getText().substring(29));
        String patenteman=txtPatenteman.getText();        
        String fec_ing=txtFechaing.getText();
        String fec_sal=txtFechasal.getText();
        int estado=comboEstado.getSelectedIndex();
        String descripcion=txtDesc.getText();
        CrudeVehiculo crudVic=new CrudeVehiculo();
        Vehiculo vic = crudVic.Buscar(patenteman);
        int kilo_man =0;
         Date fecha_ing = new Date();
         Date fecha_sal = new Date();
         Mantencion man = new Mantencion();
        boolean estado_verif = man.verificaEstado(estado);
        try{
          SimpleDateFormat formato=new SimpleDateFormat("yyyy-mm-dd");
            fecha_ing=formato.parse(fec_ing);
            fecha_sal=formato.parse(fec_sal);
        } catch(ParseException ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        man = new Mantencion(id, fecha_ing,fecha_sal,estado_verif,vic, descripcion, kilo_man);
        CrudeMantencion crudMan=new CrudeMantencion();
        crudMan.Modificar(man);
        txtPatenteman.setEditable(true);
        infoMantencion.setText("Ingreso de Mantencion");
        btnModificarManSQL.setVisible(false);
        btnIngresoman.setVisible(true);
    }//GEN-LAST:event_btnModificarManSQLActionPerformed

    private void txtVinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVinActionPerformed

    private void txtKiloMantencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKiloMantencionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKiloMantencionActionPerformed

    private void txtFechaingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaingActionPerformed
                
                
    }//GEN-LAST:event_txtFechaingActionPerformed
      
    private void txtFechasalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechasalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechasalActionPerformed

    private void comboBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBuscarActionPerformed
        // TODO add your handling code here:
                Object selected = comboBuscar.getSelectedItem();        
                if(selected.toString().equals("Cliente"))
                    txtBuscar.setText("Ingrese RUT del Cliente");
                else if(selected.toString().equals("Vehiculo"))
                   txtBuscar.setText("Ingrese la patente del Vehiculo");
                else if(selected.toString().equals("Mantencion"))
                    txtBuscar.setText("Ingrese el ID de la mantencion");
    }//GEN-LAST:event_comboBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:Object selected = comboBuscar.getSelectedItem();
                 
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Object selected = comboBuscar.getSelectedItem();        
                if(selected.toString().equals("Cliente")){
                    CrudeCliente crud=new CrudeCliente();
                    Cliente cli = new Cliente();
                    String rut = txtBuscar.getText();
                    rut = rut.substring(0, rut.length()-1);
                    rut=cli.VerificarRut(rut);
                    cli=crud.Buscar(rut);
                    tblBuscar.setModel(crud.listaClientes());
                }else if(selected.toString().equals("Vehiculo")){
                    CrudeVehiculo crud=new CrudeVehiculo();
                    Vehiculo vic  = new Vehiculo();
                    String patente = txtBuscar.getText();
                    vic=crud.Buscar(patente);
                    tblBuscar.setModel(crud.listaVehiculo());
                }else if(selected.toString().equals("Mantencion")){
                    CrudeMantencion crud=new CrudeMantencion();
                    Mantencion man  = new Mantencion();
                    int id = Integer.parseInt(txtBuscar.getText());
                     try {
                         man=new CrudeMantencion().Buscar(id);
                     } catch (ParseException ex) {
                         Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
                     }
                     tblBuscar.setModel(crud.listaMantencion());
                };
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarVehiculo;
    private javax.swing.JButton btnEliminarman;
    private javax.swing.JButton btnIngresoCliente;
    private javax.swing.JButton btnIngresoVehiculo;
    private javax.swing.JButton btnIngresoman;
    private javax.swing.JButton btnListarman;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnModificarClienteSQL;
    private javax.swing.JButton btnModificarManSQL;
    private javax.swing.JButton btnModificarVehiculo;
    private javax.swing.JButton btnModificarVehiculoSQL;
    private javax.swing.JButton btnModificarman;
    private javax.swing.JComboBox<String> comboBuscar;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel infoCliente;
    private javax.swing.JLabel infoMantencion;
    private javax.swing.JLabel infoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton listaClientes;
    private javax.swing.JButton listaClientes1;
    private javax.swing.JButton listaVehiculo;
    private javax.swing.JButton listaVehiculo1;
    private javax.swing.JTable tblBuscar;
    private javax.swing.JTable tblListaClientes;
    private javax.swing.JTable tblListaMantencion;
    private javax.swing.JTable tblListaVehiculo;
    private javax.swing.JLabel tituloDesc;
    private javax.swing.JLabel tituloDesc1;
    private javax.swing.JTextField txtAgnoFab;
    private javax.swing.JTextField txtApe1;
    private javax.swing.JTextField txtApe2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtClienteVehiculo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtDesMan;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JFormattedTextField txtFechaing;
    private javax.swing.JFormattedTextField txtFechasal;
    private javax.swing.JTextField txtKiloMantencion;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPatente;
    private javax.swing.JTextField txtPatenteman;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtVin;
    // End of variables declaration//GEN-END:variables
}
